steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

# Debugging Step: Print environment variables
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "PROJECT_ID: $PROJECT_ID"
      echo "COMMIT_SHA: $COMMIT_SHA"

# Step 3: Deploy to Cloud Run with environment variables from Secret Manager
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ACCESS_TOKEN_SECRET=$(gcloud secrets versions access latest --secret=ACCESS_TOKEN_SECRET)
      REFRESH_TOKEN_SECRET=$(gcloud secrets versions access latest --secret=REFRESH_TOKEN_SECRET)
      gcloud run deploy backend \
        --image=gcr.io/$PROJECT_ID/backend:$COMMIT_SHA \
        --platform=managed \
        --region=us-central1 \
        --allow-unauthenticated \
        --set-env-vars=ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET,REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET,PORT=8080 \
        --quiet

images:
- 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
