steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/manajamen-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/manajamen-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'manajamen-backend',
        '--image',
        'gcr.io/$PROJECT_ID/manajamen-backend',
        '--timeout',
        '1000s',
        '--port',
        '8080',  # Ensure the port is 8080
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
